apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: streaming-consumer
  name: streaming-consumer
spec:
  ports:
  - name: "9999"
    port: 9999
    targetPort: 8080
  selector:
    io.kompose.service: streaming-consumer
status:
  loadBalancer: {}
